"""initial_schema

Revision ID: 07ae0150c084
Revises: 
Create Date: 2026-02-26 22:47:01.224535
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07ae0150c084'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_number', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address_line1', sa.String(), nullable=False),
    sa.Column('address_line2', sa.String(), nullable=True),
    sa.Column('zip_city', sa.String(), nullable=False),
    sa.Column('vat_rate', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('provider_location', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('rate_currency', sa.String(), nullable=True),
    sa.Column('billing_cycle', sa.String(), nullable=False),
    sa.Column('cost_type', sa.String(), nullable=False),
    sa.Column('distribution_method', sa.String(), nullable=True),
    sa.Column('vat_status', sa.String(), nullable=False),
    sa.Column('bank_keywords', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('working_days_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('invoice_number_display', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('net_total', sa.Float(), nullable=False),
    sa.Column('vat_amount', sa.Float(), nullable=False),
    sa.Column('gross_total', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('sent_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('line_item_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('fixed_amount', sa.Float(), nullable=True),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['cost_categories.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('covers_months', sa.Text(), nullable=True),
    sa.Column('assigned_month', sa.String(), nullable=True),
    sa.Column('hours', sa.Float(), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('rate_currency', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['cost_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount_eur', sa.Float(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('account_iban', sa.String(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('provider_invoice_id', sa.Integer(), nullable=True),
    sa.Column('fx_rate', sa.Float(), nullable=True),
    sa.Column('bank_fee', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['cost_categories.id'], ),
    sa.ForeignKeyConstraint(['provider_invoice_id'], ['provider_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_invoice_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('provider_invoice_id', sa.Integer(), nullable=True),
    sa.Column('distribution_source_id', sa.Integer(), nullable=True),
    sa.Column('distribution_months_json', sa.Text(), nullable=True),
    sa.Column('upwork_tx_ids_json', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['cost_categories.id'], ),
    sa.ForeignKeyConstraint(['distribution_source_id'], ['provider_invoices.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['generated_invoices.id'], ),
    sa.ForeignKeyConstraint(['provider_invoice_id'], ['provider_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_receipts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount_eur', sa.Float(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('matched_invoice_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['matched_invoice_id'], ['generated_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upwork_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tx_id', sa.String(), nullable=False),
    sa.Column('tx_date', sa.Date(), nullable=False),
    sa.Column('tx_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('amount_eur', sa.Float(), nullable=False),
    sa.Column('freelancer_name', sa.String(), nullable=True),
    sa.Column('contract_ref', sa.String(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('assigned_month', sa.String(), nullable=True),
    sa.Column('assigned_invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_invoice_id'], ['generated_invoices.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['cost_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upwork_transactions')
    op.drop_table('payment_receipts')
    op.drop_table('generated_invoice_items')
    op.drop_table('bank_transactions')
    op.drop_table('provider_invoices')
    op.drop_table('line_item_definitions')
    op.drop_table('generated_invoices')
    op.drop_table('working_days_config')
    op.drop_table('cost_categories')
    op.drop_table('clients')
    # ### end Alembic commands ###
