"""sprint1_import_history_company_settings_client_fields

Revision ID: 40a5196c80fb
Revises: 07ae0150c084
Create Date: 2026-02-28 16:37:12.085096
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40a5196c80fb'
down_revision: Union[str, None] = '07ae0150c084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('address_line1', sa.String(), nullable=False),
    sa.Column('address_line2', sa.String(), nullable=True),
    sa.Column('zip_city', sa.String(), nullable=False),
    sa.Column('managing_director', sa.String(), nullable=True),
    sa.Column('tax_number', sa.String(), nullable=True),
    sa.Column('vat_id', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('iban', sa.String(), nullable=True),
    sa.Column('bic', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('fax', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('register_info', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('stored_path', sa.String(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('vat_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('contact_person', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('payment_terms_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('payment_terms_days')
        batch_op.drop_column('email')
        batch_op.drop_column('contact_person')
        batch_op.drop_column('vat_id')
        batch_op.drop_column('country')

    op.drop_table('import_history')
    op.drop_table('company_settings')
    # ### end Alembic commands ###
